/***************************************************************
 
 cBasic - coreBasic - BASIC Language Interpreter on iOS
 Copyright 2011 Jeremy Bridon - See License.txt for info
 
 This source file is developed and maintained by:
 + Jeremy Bridon jbridon@cores2.com
 
 File: cbCompile.h/c
 Desc: Compile the given lex-tree into the coreBasic byte-code.
 A lexical analysis tree is generated by using the parsing
 functions within "cbParse.h/c".
 
***************************************************************/

#ifndef __CBCOMPILE_H__
#define __CBCOMPILE_H__

#include "cbUtil.h"
#include "cbTypes.h"

/*** Main Compiler Entry Points ***/

// Compile the given symbol table's lex tree into byte-code
bool cbParse_CompileProgram(cbSymbolsTable* SymbolsTable, cbList* ErrorList, cbVirtualMachine* Process);

// Build code by traversing the lex-tree left-right then inside (ops)
void cbParse_BuildNode(cbSymbolsTable* SymbolsTable, cbLexNode* Node, cbList* ErrorList);

// End if inclusion guard
#endif
